spring:
  datasource:
    url: jdbc:mariadb://myemojipublic.cp4filjorlx3.ap-northeast-2.rds.amazonaws.com/myemoji
    driver-class-name: org.mariadb.jdbc.Driver
    username: eui
    password: myemoji2023
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: false
    hibernate:
      ddl-auto: update

oauth2:
  google:
    client-id: 229700534077-ha2l7ee5fnpp7jv4tinbsd40dqij7qe8.apps.googleusercontent.com
    client-secret: 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
    redirect-uri: http://ec2-3-34-178-125.ap-northeast-2.compute.amazonaws.com:8080/login/oauth2/code/google
    token-uri: https://oauth2.googleapis.com/token
    resource-uri: https://www.googleapis.com/oauth2/v2/userinfo
